version: '3'
services:
    app:
        container_name: node-typescript-starter-template
        restart: always
        build: .
        ports:
            - '80:5000'
        external_links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
