version: '3'
services:
  app:
    container_name: node-typescript-starter-template
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
